apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: quay-io
    image: quay.io/jetstack/cert-manager:v1.4.1
  - name: ghrc-io
    image: ghcr.io/heptio-images/eventrouter:v0.3
