apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
  namespace: default
spec:
  containers:
  - image: harbor.myco.com/docker.io/nginx:latest
    name: docker-library

---

