apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
  namespace: default
spec:
  containers:
  - image: harbor.myco.com/ghcr.io/heptio-images/eventrouter:v0.3
    name: ghrc-io

---

