apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: myapp-pod
  namespace: default
spec:
  containers:
  - image: harbor.myco.com/quay.io/jetstack/cert-manager:v1.4.1
    name: quay-io

---

